core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("events.urls")),
    path("", include("authuser.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    EventListView,
    EventItemsListView,
    ItemDetailView,
    OrderSummaryView,
    CheckoutView,
    ThankYouView,
    ShopView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
)

app_name = "events"

urlpatterns = [
    path("", EventListView.as_view(), name="events"),
    path("events/<str:slug>", EventItemsListView.as_view(), name="event_items"),
    path("items", ItemDetailView.as_view(), name="items"),
    path("items/<str:slug>", ItemDetailView.as_view(), name="item_details"),
    path("add-to-cart/<str:slug>", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path(
        "remove-single-item-from-cart/<slug>",
        remove_single_item_from_cart,
        name="remove-single-item-from-cart",
    ),
    path("order-summary", OrderSummaryView.as_view(), name="order-summary"),
    path("checkout", CheckoutView.as_view(), name="checkout"),
    path("thanks", ThankYouView.as_view(), name="thanks"),
    path("about", TemplateView.as_view(template_name="core/about.html"), name="about"),
    path("shop", ShopView.as_view(), name="shop"),
    path(
        "contact",
        TemplateView.as_view(template_name="core/contact.html"),
        name="contact",
    ),
]

events/models.py
from django.db import models
from django.shortcuts import reverse  # type: ignore
from django.conf import settings


class EventType(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="event_type")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:event_items", kwargs={"slug": self.slug})


class Item(models.Model):
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    discount_price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    event_types = models.ManyToManyField(EventType)
    image = models.ImageField(upload_to="items")
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events:item_details", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("events:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("events:remove-from-cart", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey("Item", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    is_ordered = models.BooleanField(default=False)
    address = models.ForeignKey(
        "Address",
        related_name="address",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    coupon = models.ForeignKey(
        "Coupon", on_delete=models.CASCADE, blank=True, null=True
    )
    is_delivered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_cart_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100, null=True)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Addresses"


class Coupon(models.Model):
    code = models.CharField(max_length=10)
    amount = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.code

events/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

from .models import EventType, Item, Order, OrderItem


class ItemsListView(ListView):
    model = Item
    context_object_name = "items"
    template_name = "events/items_list.html"


class EventListView(ListView):
    model = EventType
    context_object_name = "event_types"
    template_name = "core/homepage.html"


class EventItemsListView(ListView):
    context_object_name = "items"
    template_name = "events/items_list.html"

    def get_queryset(self):
        self.event_type = get_object_or_404(EventType, slug=self.kwargs["slug"])
        return Item.objects.filter(event_types=self.event_type)


class ItemDetailView(DetailView):
    model = Item
    context_object_name = "item"
    template_name = "events/item_detail.html"


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, is_ordered=False)
            context = {"cart": order}
            return render(self.request, "events/order_summary.html", context)
        except ObjectDoesNotExist:
            # messages.warning(self.request, "You don't have any active order!!")
            return redirect("/")


class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, is_ordered=False)
            context = {"cart": order}
        except ObjectDoesNotExist:
            # messages.info(self.request, "Currently you don't have any ordrs")
            return redirect("/")

        return render(self.request, "events/checkout.html", context)


class ShopView(ListView):
    model = Item
    context_object_name = "items"
    template_name = "events/items_list.html"


class ThankYouView(DetailView):
    def get(self, *args, **kwargs):
        return render(
            self.request,
            "events/thanks.html",
        )

    def post(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, is_ordered=False)
            order.is_ordered = True
            order.save()
        except ObjectDoesNotExist:
            pass

        return render(
            self.request,
            "events/thanks.html",
        )


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item, user=request.user, is_ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    print(order_qs)

    if order_qs.exists():
        order = order_qs[0]

        # check if the item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            print(order_item.quantity)
            order_item.quantity += 1
            order_item.save()
            # messages.info(request, "This item quantity was updated")
            return redirect("events:order-summary")
        else:
            # messages.info(request, "This item is added to your cart")
            order.items.add(order_item)
            return redirect("events:order-summary")
    else:
        print("creating")
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        # messages.info(request, "This item is added to your cart")
        order.items.add(order_item)
        return redirect("events:order-summary")


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # check if the item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, is_ordered=False
            )[0]
            order_item.quantity = 1
            order_item.save()
            order.items.remove(order_item)
            # messages.info(request, "This item is removed from your cart")
            return redirect("events:order-summary")
        else:
            # messages.info(request, "This item is not in your cart")
            return redirect("events:item_details", slug=slug)
    else:
        # messages.info(request, "You don't have any order yet.")
        return redirect("events:item_details", slug=slug)


@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # check if the item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item, user=request.user, is_ordered=False
            )[0]

            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            # messages.info(request, "This item is updated");
            return redirect("events:order-summary")
        else:
            # messages.info(request, "This item is not in your cart");
            return redirect("event:item_details", slug=slug)
    else:
        # messages.info(request, "You don't have any order yet.");
        return redirect("event:item_details", slug=slug)

events/templates/events/checkout.html
{% extends "base.html" %}
{% block content %}
  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mb-5 mb-md-0">
          <h2 class="h3 mb-3 text-black">Shipping Details</h2>
          <div class="p-3 p-lg-5 border">
            <div class="form-group">
              <label for="c_country" class="text-black">
                Country <span class="text-danger">*</span>
              </label>
              <select id="c_country" class="form-control">
                <option value="1">
                  Select a country
                </option>
                <option value="2">
                  Saudi Arabia
                </option>
                <option value="3">
                  Syria
                </option>
                <option value="4">
                  Yemen
                </option>
                <option value="5">
                  Turkey
                </option>
                <option value="6">
                  Dubai
                </option>
                <option value="7">
                  Kuwait
                </option>
              </select>
            </div>
            <div class="form-group row">
              <div class="col-md-12">
                <label for="c_address" class="text-black">
                  Address <span class="text-danger">*</span>
                </label>
                <input type="text"
                       class="form-control"
                       id="c_address"
                       name="c_address"
                       placeholder="Street address">
              </div>
            </div>
            <div class="form-group">
              <input type="text"
                     class="form-control"
                     placeholder="Apartment, suite, unit etc. (optional)">
            </div>
            <div class="form-group row">
              <div class="col-md-6">
                <label for="c_state_country" class="text-black">
                  State / Country <span class="text-danger">*</span>
                </label>
                <input type="text"
                       class="form-control"
                       id="c_state_country"
                       name="c_state_country">
              </div>
              <div class="col-md-6">
                <label for="c_postal_zip" class="text-black">
                  Posta / Zip <span class="text-danger">*</span>
                </label>
                <input type="text"
                       class="form-control"
                       id="c_postal_zip"
                       name="c_postal_zip">
              </div>
            </div>
            <div class="form-group">
              <label for="c_order_notes" class="text-black">Order Notes</label>
              <textarea name="c_order_notes"
                        id="c_order_notes"
                        cols="30"
                        rows="5"
                        class="form-control"
                        placeholder="Write your notes here..."></textarea>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row mb-5">
            <div class="col-md-12">
              <h2 class="h3 mb-3 text-black">Your Order</h2>
              <div class="p-3 p-lg-5 border">
                <table class="table site-block-order-table mb-5">
                  <thead>
                    <th>Product</th>
                    <th>Total</th>
                  </thead>
                  <tbody>
                    {% for order_item in cart.items.all %}
                      <tr>
                        <td>
                          {{ order_item.item.title }} <strong class="mx-2">x</strong> {{ order_item.quantity }}
                        </td>
                        <td>
                          {% if order_item.item.discount_price %}
                            {{ order_item.get_total_discount_item_price }}
                          {% else %}
                            {{ order_item.get_total_item_price }}
                          {% endif %}
                        </td>
                      </tr>
                    {% empty %}
                      <tr>
                        <td>Cart is empty</td>
                      </tr>
                    {% endfor %}
                    <tr>
                      <td class="text-black font-weight-bold">
                        <strong>Order Total</strong>
                      </td>
                      <td class="text-black font-weight-bold">
                        <strong>{{ cart.get_cart_total }}</strong>
                      </td>
                    </tr>
                  </tbody>
                </table>
                <div class="form-group">
                  <form method="post" action="{% url 'events:thanks' %}">
                    {% csrf_token %}
                    <input type="submit"
                           class="btn btn-primary btn-lg py-3 btn-block"
                           value="Place Order"/>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

events/templates/events/events_list.html
<div class="site-section site-blocks-2">
  <div class="container">
    <div class="row">
      {% for event_type in event_types %}
        <div class="col-sm-6 col-md-6 col-lg-4 mb-4"
             data-aos="fade"
             data-aos-delay="">
          <a class="block-2-item" href="{{ event_type.get_absolute_url }}">
            <figure class="image">
              <img src="{{ event_type.image.url }}"
                   alt=""
                   class="event-card-img"
                   width="auto"
                   height="auto"/>
            </figure>
            <div class="text">
              <h3>{{ event_type.title }}</h3>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

events/templates/events/featured_items_list.html
<div class="site-section block-3 site-blocks-2 bg-light">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-7 site-section-heading text-center pt-4">
        <h2>Featured Products</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="nonloop-block-3 owl-carousel">
          {% for item in featured_items %}
            <div class="item">
              <div class="block-4 text-center">
                <figure class="block-4-image">
                  <img src="{{ item.image.url }}" alt="{{ item.title }}" class="img-fluid">
                </figure>
                <div class="block-4-text p-4">
                  <h3>
                    <a href='{{ item.get_absolute_url }}'>{{ item.title }}</a>
                  </h3>
                  <p class="mb-0">{{ item.description }}</p>
                  <p class="text-primary font-weight-bold">{{ item.price }}</p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

events/templates/events/item_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="site-section">
    <div class="container mb-5">
      <div class="row">
        <div class="col-md-6">
          <img src="{{ item.image.url }}"
               alt="{{ item.title }}"
               class="img-fluid"
               width="auto"
               height="auto"/>
        </div>
        <div class="col-md-6">
          <h2 class="text-black">{{ item.title }}</h2>
          <p>{{ item.description }}</p>
          <p>
            <strong class="text-primary h4">{{ item.price }}</strong>
          </p>
          <div class="mb-5">
            <div class="input-group mb-3" style="max-width: 120px;">
              <div class="input-group-prepend">
                <a href="{% url 'events:remove-single-item-from-cart' item.slug %}"
                   class="buy-now btn btn-block btn-outline-primary">-</a>
              </div>
              <input type="text"
                     class="form-control text-center"
                     value="1"
                     placeholder=""
                     disabled/>
              <div class="input-group-append">
                <a href="{{ item.get_add_to_cart_url }}"
                   class="buy-now btn btn-block btn-outline-primary">+</a>
              </div>
            </div>
          </div>
          <p>
            <a href="{{ item.get_add_to_cart_url }}"
               class="buy-now btn btn-sm btn-primary">Add To Cart</a>
          </p>
        </div>
      </div>
    </div>
    {% include "events/featured_items_list.html" %}
  </div>
{% endblock content %}

events/templates/events/items_list.html
{% extends "base.html" %}
{% block content %}
  <div class="site-section">
    <div class="container">
      <div class="row mb-5">
        {% for item in items %}
          <a href='{{ item.get_absolute_url }}'>
            <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
              <div class="block-4 text-center border">
                <figure class="block-4-image">
                  <a href='{{ item.get_absolute_url }}'>
                    <img src='{{ item.image.url }}'
                         alt='{{ item.title }}'
                         class="item-card-img"/>
                  </a>
                </figure>
                <div class="block-4-text p-4">
                  <h3>
                    <a href='{{ item.get_absolute_url }}'>{{ item.title }}</a>
                  </h3>
                  <div class="row justify-content-center">
                    <span class="text-primary font-weight-bold">{{ item.price }}</span>
                  </div>
                </div>
              </div>
            </div>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

events/templates/events/order_summary.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="site-section">
    <div class="container">
      <div class="col-md-12">
        <h2 class="h3 mb-5 text-black text-center">Order Summary</h2>
      </div>
      <div class="row mb-5">
        <form class="col-md-12" method="post">
          <div class="site-blocks-table">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th class="product-thumbnail">Image</th>
                  <th class="product-name">Product</th>
                  <th class="product-price">Price</th>
                  <th class="product-quantity">Quantity</th>
                  <th class="product-total">Total</th>
                  <th class="product-remove">Remove</th>
                </tr>
              </thead>
              <tbody>
                {% for order_item in cart.items.all %}
                  <tr>
                    <td class="product-thumbnail">
                      <img src="{{ order_item.item.image.url }}" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">{{ order_item.item.title }}</h2>
                    </td>
                    <td>
                      {% if order_item.item.discount_price %}
                        {{ order_item.item.discount_price }}
                      {% else %}
                        {{ order_item.item.price }}
                      {% endif %}
                    </td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <a href="{% url 'events:remove-single-item-from-cart' order_item.item.slug %}"
                             class="buy-now btn btn-block btn-outline-primary">-</a>
                        </div>
                        <input type="text"
                               class="form-control text-center"
                               value="{{ order_item.quantity }}"
                               placeholder="0"
                               disabled/>
                        <div class="input-group-append">
                          <a href="{% url 'events:add-to-cart' order_item.item.slug %}"
                             class="buy-now btn btn-block btn-outline-primary">+</a>
                        </div>
                      </div>
                    </td>
                    <td>
                      {% if order_item.item.discount_price %}
                        {{ order_item.get_total_discount_item_price }}
                      {% else %}
                        {{ order_item.get_total_item_price }}
                      {% endif %}
                    </td>
                    <td>
                      <a href="{% url 'events:remove-from-cart' order_item.item.slug %}"
                         class="btn btn-primary btn-sm">X</a>
                    </td>
                  </tr>
                {% empty %}
                  <tr>
                    <td colspan=6>Your cart is empty</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </form>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="row mb-5">
            <div class="col-md-6 mb-3 mb-md-0">
              <button class="btn btn-primary btn-sm btn-block">Update Cart</button>
            </div>
            <div class="col-md-6">
              <a href="{% url 'events:events' %}"
                 class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 pl-5">
          <div class="row justify-content-end">
            <div class="col-md-7">
              <div class="row">
                <div class="col-md-12 text-right border-bottom mb-5">
                  <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                </div>
              </div>
              <div class="row mb-5">
                <div class="col-md-6">
                  <span class="text-black">Total</span>
                </div>
                <div class="col-md-6 text-right">
                  <strong class="text-black">{{ cart.get_cart_total }}</strong>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <a href="{% url 'events:checkout' %}"
                     class="btn btn-primary btn-lg py-3 btn-block">Proceed To Checkout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

events/templates/events/thanks.html
{% extends "base.html" %}
{% block content %}
  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <span class="icon-check_circle display-3 text-success"></span>
          <h2 class="display-3 text-black">Thank you!</h2>
          <p class="lead mb-5">You order was successfuly completed.</p>
          <p>
            <a href="{% url 'events:events' %}" class="btn btn-sm btn-primary">Back to shop</a>
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}