authuser/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import register_view

app_name = "authuser"

urlpatterns = [
    path("register", register_view, name="register"),
    path(
        "login",
        auth_views.LoginView.as_view(
            template_name="authuser/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("events.urls")),
    path("", include("authuser.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    EventListView,
    EventItemsListView,
    ItemDetailView,
    OrderSummaryView,
    CheckoutView,
    ThankYouView,
    ShopView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
)

app_name = "events"

urlpatterns = [
    path("", EventListView.as_view(), name="events"),
    path("events/<str:slug>", EventItemsListView.as_view(), name="event_items"),
    path("items", ItemDetailView.as_view(), name="items"),
    path("items/<str:slug>", ItemDetailView.as_view(), name="item_details"),
    path("add-to-cart/<str:slug>", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path(
        "remove-single-item-from-cart/<slug>",
        remove_single_item_from_cart,
        name="remove-single-item-from-cart",
    ),
    path("order-summary", OrderSummaryView.as_view(), name="order-summary"),
    path("checkout", CheckoutView.as_view(), name="checkout"),
    path("thanks", ThankYouView.as_view(), name="thanks"),
    path("about", TemplateView.as_view(template_name="core/about.html"), name="about"),
    path("shop", ShopView.as_view(), name="shop"),
    path(
        "contact",
        TemplateView.as_view(template_name="core/contact.html"),
        name="contact",
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Party Pile</title>
    <title>
      {% block head_title %}
      {% endblock head_title %}
    </title>
    {% block extra_head %}
    {% endblock extra_head %}
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"/>
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/aos.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block pageSpecificCSS %}
    {% endblock pageSpecificCSS %}
  </head>
  <body>
    <div class="site-wrap">
      {% include "navbar.html" %}
      {% if messages %}
        <div class="mt-5 pt-4">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                 role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">X</span>
              </button>
            </div>
          {% endfor %}
        </div>
      {% endif %}
      {% block content %}
      {% endblock content %}
      {% include "footer.html" %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/jquery-ui.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'js/aos.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>
      <script src="{% static 'js/form_validation.js' %}"></script>
      {% block pageSpecificJS %}
      {% endblock pageSpecificJS %}
    </div>
  </body>
</html>

templates/footer.html
<footer class="site-footer border-top">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-lg-8 mb-5 mb-lg-0">
        <div class="row">
          <div class="col-md-6 col-lg-4">
            <h3 class="footer-heading mb-4">Navigations</h3>
            <ul class="list-unstyled">
              <li>
                <a href="{% url 'events:events' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'events:about' %}">About</a>
              </li>
              <li>
                <a href="{% url 'events:shop' %}">Shop</a>
              </li>
              <li>
                <a href="{% url 'events:contact' %}">Contact</a>
              </li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-4">
            <h3 class="footer-heading mb-4">Parties</h3>
            <ul class="list-unstyled">
              {% for type in event_types %}
                <li>
                  <a href="{% url 'events:event_items' type.slug %}">{{ type.title }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-4">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>
          <ul class="list-unstyled">
            <li class="address">A/203 - Hail, Saudi Arabia</li>
            <li class="phone">
              <a href="tel://9669876543">+966 9876 543</a>
            </li>
            <li class="email">emailaddress@domain.com</li>
          </ul>
        </div>
        <div class="block-7">
          <div>
            <label for="email_subscribe" class="footer-heading">Subscribe</label>
            <div class="form-group">
              <input type="text"
                     class="form-control py-4"
                     id="email_subscribe"
                     placeholder="Email"/>
              <input type="submit" class="btn btn-sm btn-primary" value="Send" />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <p>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;<script data-cfasync="false"
        src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>
    </div>
  </div>
</footer>

templates/navbar.html
{% load static %}
{% load cart_template_tags %}
<header class="site-navbar" role="banner">
  <div class="site-navbar-top">
    <div class="container">
      <div class="row align-items-center justify-content-between">
        <div class="order-2 order-md-1 site-search-icon text-left">
          <div class="site-logo">
            <a href="{% url 'events:events' %}"  class="js-logo-clone">
              <img src="{% static 'images/logo.png' %}" width="200" height="auto" alt="" />
            </a>
          </div>
        </div>
        <div class="mb-3 mb-md-0 order-1 order-md-2 text-center">
          <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
              <ul class="site-menu js-clone-nav d-none d-md-block">
                <li class="active">
                  <a href="{% url 'events:events' %}">Home</a>
                </li>
                <li>
                  <a href="{% url 'events:about' %}">About</a>
                </li>
                <li>
                  <a href="{% url 'events:shop' %}">Shop</a>
                </li>
                <li>
                  <a href="{% url 'events:contact' %}">Contact</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
        <div class="order-3 order-md-3 text-right">
          <div class="site-top-icons site-navigation text-right text-md-center">
            <ul class="site-menu js-clone-nav d-none d-md-block">
              {% if user.is_authenticated %}
                <li class="has-children">
                  <a>Hi, {{ user.username }}</a>
                  <ul class="dropdown">
                    <li>
                      <a href="{% url 'authuser:logout' %}">Log out</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a href="{% url 'events:order-summary' %}" class="site-cart">
                    <span class="icon icon-shopping_cart"></span>
                    <span class="count">{{ request.user|cart_item_count }}</span>
                  </a>
                </li>
                <li class="d-inline-block d-md-none ml-md-0">
                  <a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a>
                </li>
              {% else %}
                <a class="btn btn-success"
                   style="color: #fff"
                   href="{% url 'authuser:login' %}"><span>Login</span></a>
                <a class="btn btn-secondary" href="{% url 'authuser:register' %}"><span>Register</span></a>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>